### ISSUE TITLE
Fix time on the web server or the netbox instance

### ISSUE THREAD

**Issue by shawfdong** [lbnl-science-it/hpcs-netbox#15]
The time on the web server or the netbox instance seems to be off by 8 hours. For example, 
https://hpcs-netbox.lbl.gov/dcim/devices/146/changelog/

It says n00039.lr5 was "Created 2022-02-15 · Updated 9 hours, 5 minutes ago". The timestamp was "2022-02-15 09:24". However, the current local time was about 10:29am (PST). Perhaps the the web server or the netbox instance is using UTC?

**Comment by ak-lbl** [comment]
the TIME_ZONE parameter (which defaults to UTC) has been changed to 'America/Los_Angeles' in /opt/netbox/netbox/netbox/configuration.py

to reiterate, this setting is independent from the symlink in /etc/localtime.
